---
- hosts: "{{ lookup('env', 'SERVER1') }}:{{ lookup('env', 'SERVER2') }}"
  vars:
    ansible_ssh_private_key_file: "/data/id_rsa"
  pre_tasks:
    - apt:
        update_cache: yes
    - name: Create files/mysql
      copy:
        content: "{{ lookup('env', 'BACKUP_KEY') }}"
        dest: "./key"
      delegate_to: localhost
  roles:
    - role: cluster
      cluser_user_password: "{{ lookup('env', 'CLUSTER_USER_PASSWORD') }}"
      clustername: mysql
      ini_file: /data/cluster.ini
    - role: hetzner_cloud_stonith
      api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
      disable_stonith: false
    - role: cloud_floating_ip
      api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
      floating_ip: "{{ hostvars.localhost.created_floating_ip.ip }}"
      permanent: false
      ip_name: "{{ lookup('env', 'FLOATING_IP') }}"
      ip_nic: "{{ ansible_default_ipv4.interface }}"
    - role: drbd
      resource_level_fencing: true
      drbd_hosts:
        - "{{ lookup('env', 'SERVER1') }}"
        - "{{ lookup('env', 'SERVER2') }}"
      devices:
        - name: mysql
          disk_device: /dev/vg0/mysql
          drbd_device: /dev/drbd_mysql
          port: 7788
          minor: 0
          format: ext4
    - role: cluster_drbd
      devices:
        - name: mysql
          dev: drbd_mysql
          mnt: /mnt/mysql
          conf: /etc/drbd.d/mysql.res
          drbd_name: mysql
          format: ext4
          colocation_ip: "{{ lookup('env', 'FLOATING_IP') }}"
    - role: mariadb
      innodb_buffer_pool_size: "{{ 'innodb_buffer_pool_size  section='~lookup('ini', lookup('env', 'SERVER_TYPE')~' file=server_types.ini') }}"
      innodb_log_file_size: 512M
      data_path: /mnt/mysql
      bind_address: "{{ hostvars.localhost.created_floating_ip.ip }}"
    - role: mariadb_cluster
      key_directory: .
      constraint_service: mysql-master
      databases: []
      users:
        - name: "{{ lookup('env', 'ADMIN_USERNAME') }}"
          password: "{{ lookup('env', 'ADMIN_PASSWORD') }}"
          host: "%"
          privileges:
            - table: '*.*'
              privileges: 
                - ALL
                - GRANT
    - role: mysql_backup
      plugin: scp
      log: 4
      datadir: "/mnt/mysql"
      database_connect: "--socket=/var/lib/mysqld/mysqld.sock"
      sftp_user: "{{ lookup('env', 'BACKUP_USER') }}"
      sftp_server: "sftp://{{ lookup('env', 'BACKUP_SERVER') }}"
      sftp_root_directory: "{{ lookup('env', 'BACKUP_PATH') }}"
    - role: mysql_backup_cluster
