---
- hosts: localhost
  gather_facts: false
  roles:
    - role: hcloud_create_ip
      ip_description: "{{ lookup('env', 'FLOATING_IP') }}"
    - name: create_ssh_key
      key_path: "/data/id_rsa"
  post_tasks:
  - name: Create key
    hcloud_ssh_key:
      name: mysql_key
      public_key: "{{ lookup('file', '/data/id_rsa.pub') }}"
      state: present
  - name: Create servers
    hcloud_server:
      name: "{{ item }}"
      state: present
      image: debian-9
      server_type: "{{ lookup('env', 'SERVER_TYPE') }}"
      location: "{{ lookup('env', 'SERVER_LOCATION') }}"
      ssh_keys:
      - mysql_key
    register: create_servers
    loop:
      - "{{ lookup('env', 'SERVER1') }}"
      - "{{ lookup('env', 'SERVER2') }}"
  - name: Set newly created servers into rescue mode
    hcloud_server:
      name: "{{ item.item }}"
      rescue: linux64
      ssh_keys:
      - mysql_key
    when: item.changed
    loop: {{ create_servers.results }}
  - name: Refresh inventory with new servers
    meta: refresh_inventory
  - name: Wait for a few seconds for the new servers to start ssh
    wait_for:
      timeout: 30
    when: create_servers.changed
