- hosts: "{{ lookup('env', 'SERVER1') }}:{{ lookup('env', 'SERVER2') }}"
  max_fail_percentage: 0
  vars:
    ansible_ssh_private_key_file: "/data/id_rsa"
  roles:
    - role: provision
      volumes:
      - name: root
        mountpoint: /
        fs: ext4
        size: 10G
    - role: logical_volumes
      group: vg0
      volumes:
        - name: mysql
          size: 100%FREE
  post_tasks:
    - name: add  extra pubkeys
      authorized_key:
        key: "{{ lookup('env', 'SSH_EXTRA_PUBKEYS') }}"
        user: root
      when: lookup('env', 'SSH_EXTRA_PUBKEYS') != ""
