- hosts: "{{ lookup('env', 'SERVER1') }}:{{ lookup('env', 'SERVER2') }}`"
  vars:
    ansible_ssh_private_key_file: "/data/id_rsa"
  roles:
    - role: provision
      volumes:
      - name: root
        mountpoint: /
        fs: ext4
        size: 10G
    - role: logical_volumes
      volumes:
        group: vg0
        name: mysql
      size: 100%FREE
