- hosts: "{{ lookup('env', 'SERVER1') }}:{{ lookup('env', 'SERVER2') }}"
  max_fail_percentage: 0
  vars:
    ansible_ssh_private_key_file: "/data/id_rsa"
  roles:
    - role: rancher_external
      stack_name: "{{ lookup('env', 'EXTERNAL_STACK')}}"
      external_name: "{{ lookup('env', 'EXTERNAL_NAME')}}"
      external_ips: 
      - "{{ hostvars.localhost.created_floating_ip.ip }}"
      rancher:
        url: "{{ lookup('env', 'CATTLE_URL')}}"
        access_key: "{{ lookup('env', 'CATTLE_ENVIRONMENT_ADMIN_ACCESS_KEY')}}"
        secret_key: "{{ lookup('env', 'CATTLE_ENVIRONMENT_ADMIN_SECRET_KEY')}}"
